[package]
name = "blueprint"
version = "0.2.0"
edition = "2021"
description = "Static state machine / protocol blueprints"
homepage = "https://github.com/yaws-rs/blueprint"
keywords = ["io", "uring", "epoll", "async"]
license = "Apache-2.0/MIT"
readme = "README.md"
repository = "https://github.com/yaws-rs/blueprint"
categories = ["science"]

[dependencies]
#rand_core = { version = "0.10" }

[features]
default = []
#default = ["typed", "untyped"]
std = []
#typed = []
#untyped = []

[package.metadata.docs.rs]
features = []
#features = ["typed", "untyped"]
